dependencies {
    implementation 'org.firstinspires.ftc:RobotCore:10.3.0'
    implementation 'org.firstinspires.ftc:Hardware:10.3.0'
    implementation 'com.pedropathing:ftc:2.0.0'
    implementation 'com.bylazar:fullpanels:1.0.2'
}

repositories {
    maven { url = 'https://maven.pedropathing.com' }
    maven { url = "https://mymaven.bylazar.com/releases" }
}
